[package]
name = "spaghetti"
version = "0.1.0"
authors = ["John Dowson <dowson.john.pony@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4"
maud = { version = "0.22", features = ["rocket"] }
pulldown-cmark = "0.7"
diesel = { version = "1.4", features = ["sqlite", "r2d2"] }
serde = { version = "1.0", features = ["derive"] }
[dependencies.rocket_contrib]
version = "0.4"
default-features = false
features = ["serve", "diesel_sqlite_pool"]